remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/default.css"
locale: "en_US"
title: "Jay Cuthrell jaycuthrell.com"
url: "https://jaycuthrell.com"
absolute_url: "https://jaycuthrell.com"
baseurl: ""
name: "Jay Cuthrell"
description: "jaycuthrell.com"
logo: "/images/jaycuthrell.jpg"
search: false 
search_full_content: true
read_time: true
words_per_minute: 200
location: "USA"

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"


compress_html:
  clippings: all
  startings: [html, head, body]

analytics: 
  provider: google

bing_site_verification: "0081F9215265B8A63E46065BC9F094FA"
google_site_verification: "kRIQtgrJdRIqXieQD4fef0H2A-ejkIayF78XcMBjUbI"

include:
  - .htaccess
  - robots.txt
  - .well_known
  - _pages
  - _redirects

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

source:
root: /
permalink: /:title/

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

date_format: "%B %-d, %Y"
mathjax: false 

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jemoji

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

author:
  name: Jay Cuthrell
  bio: "Corporate Free Safety"
  avatar: "/images/apple-touch-icon-180x180.png" 
  location: "USA"
  links:
    - label: "Keybase"
      icon: "fab fa-keybase"
      url: "https://keybase.io/jaycuthrell"
    - label: "Mastodon"
      icon: "fa-brands fa-mastodon"
      url: "https://cuthrell.com/@jay"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jaycuthrell"
    - label: "Blog"
      icon: "fas fa-link"
      url: "https://fudge.org"
    - label: "Linkedin"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/jaycuthrell"
    - label: "Phone"
      icon: "fas fa-mobile-alt"
      url: "https://jaycuthrell.com/contact/"
    - label: "Email"
      icon: "far fa-envelope"
      url: "https://jaycuthrell.com/contact/"

owner:
  avatar: /images/jaycuthrell-headshot-300x300.jpg
  name : Jay Cuthrell
  email : jay@cuthrell.com
  github : jaycuthrell

social:
  name: Jay Cuthrell
  links:
    - https://twitter.com/JayCuthrell
    - https://www.linkedin.com/in/JayCuthrell
    - https://github.com/JayCuthrell
    - https://keybase.io/JayCuthrell

twitter:
  username: JayCuthrell
  card: summary

pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Jay Cuthrell'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      related: true
      image: /images/jaycuthrell.jpg
      header:
        image: /images/jaycuthrell.jpg
